### ISSUE TITLE
Session not saving

### ISSUE THREAD

**Issue by chronosirius** [pallets-eco/flask-session#143] opened 2022-08-06 15:24 UTC
I am storing a session in a websocket event but then when I try to use it again in an HTTP request it is empty. I printed out the sessions in the websocket and the subsequent HTTP request. After filling the session and printing it, it is a dictionary, but in the http request, it is <FileSystemSession {}> I linked an image. I am using Windows. It seems to store with http requests but not websocket ones.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/73508925/183255372-55ae1969-4c42-4b2b-9b88-d57506007942.png">

**Comment by Lxstr** [comment] 2024-02-25 07:07
Do you have a minimum reproducable example I can try? When I use websockets it stores the session fine

**Comment by Lxstr** [comment] 2024-02-27 06:41
Closing due to not reproduceable

**Closed by Lxstr** 2024-02-27 06:41 UTC
